### ISSUE TITLE
Seems it does not support 2-byte-charactor encoding

### ISSUE THREAD

**Issue by snakehnb** [danieltmbr/Bencode#8]
`Bencode(file: torrentUrl)` returns nil when `torrentUrl` refers to a torrent file encoded with 2-byte-charator encoding such as Chinese language. 
A test file attached:
[test.torrent.zip](https://github.com/danieltmbr/Bencode/files/1765218/test.torrent.zip)

**Comment by danieltmbr** [comment]
Nice catch. Going to work on that! Thanks!
